// app/layout.tsx
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/app/globals.css';
import SideNav from '@/app/ui/SideNav';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'My App',
    description: 'Generated by create next app',
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (

        <div className={`${inter.className} bg-gray-50 dark:bg-gray-950`}>
        <div className="flex h-screen w-screen">
            <SideNav />
            <main className="flex-1 overflow-auto md:ml-64 p-6">
                {children}
            </main>
        </div>
        </div>

    );
}